export * from './activiteRestController.service';
import { ActiviteRestControllerService } from './activiteRestController.service';
export * from './administrationController.service';
import { AdministrationControllerService } from './administrationController.service';
export * from './authRestController.service';
import { AuthRestControllerService } from './authRestController.service';
export * from './candidateRestController.service';
import { CandidateRestControllerService } from './candidateRestController.service';
export * from './cityRestController.service';
import { CityRestControllerService } from './cityRestController.service';
export * from './comptes.service';
import { ComptesService } from './comptes.service';
export * from './contactRestController.service';
import { ContactRestControllerService } from './contactRestController.service';
export * from './fileRestController.service';
import { FileRestControllerService } from './fileRestController.service';
export * from './menuItemRestController.service';
import { MenuItemRestControllerService } from './menuItemRestController.service';
export * from './menuRestController.service';
import { MenuRestControllerService } from './menuRestController.service';
export * from './parentFeedbackRestController.service';
import { ParentFeedbackRestControllerService } from './parentFeedbackRestController.service';
export * from './passwordResetController.service';
import { PasswordResetControllerService } from './passwordResetController.service';
export * from './paymentRestController.service';
import { PaymentRestControllerService } from './paymentRestController.service';
export * from './personRestController.service';
import { PersonRestControllerService } from './personRestController.service';
export * from './preinscriptionRestController.service';
import { PreinscriptionRestControllerService } from './preinscriptionRestController.service';
export * from './protocoleRestController.service';
import { ProtocoleRestControllerService } from './protocoleRestController.service';
export * from './rapportRestController.service';
import { RapportRestControllerService } from './rapportRestController.service';
export * from './roleRestController.service';
import { RoleRestControllerService } from './roleRestController.service';
export * from './structureRestController.service';
import { StructureRestControllerService } from './structureRestController.service';
export * from './workingSessionController.service';
import { WorkingSessionControllerService } from './workingSessionController.service';
export const APIS = [ActiviteRestControllerService, AdministrationControllerService, AuthRestControllerService, CandidateRestControllerService, CityRestControllerService, ComptesService, ContactRestControllerService, FileRestControllerService, MenuItemRestControllerService, MenuRestControllerService, ParentFeedbackRestControllerService, PasswordResetControllerService, PaymentRestControllerService, PersonRestControllerService, PreinscriptionRestControllerService, ProtocoleRestControllerService, RapportRestControllerService, RoleRestControllerService, StructureRestControllerService, WorkingSessionControllerService];
