/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreinscriptionDto } from './preinscriptionDto';


export interface ApiResponseListPreinscriptionDto { 
    success?: boolean;
    data?: Array<PreinscriptionDto>;
    message?: string;
}

