/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuItemDto } from './menuItemDto';


export interface ApiResponseListMenuItemDto { 
    success?: boolean;
    data?: Array<MenuItemDto>;
    message?: string;
}

