/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Structure } from './structure';


export interface Candidate { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    mobile?: string;
    statut?: string;
    createdAt?: string;
    getcv?: string;
    motivation?: string;
    contract?: string;
    city?: string;
    dateFree?: string;
    structures?: Set<Structure>;
}

