/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CandidateDto { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    mobile?: string;
    statut?: string;
    createdAt?: string;
    cv?: string;
    motivation?: string;
    city?: string;
    contract?: string;
    dateFree?: string;
    structureId?: number;
}

