/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Parent } from './parent';
import { Horaire } from './horaire';


export interface Child { 
    id?: number;
    lastName?: string;
    firstName?: string;
    dateBirth?: string;
    entryDate?: string;
    observation?: string;
    daysOfCare?: Array<string>;
    formula?: string;
    horaires?: Set<Horaire>;
    parent?: Parent;
    genre?: string;
}

