/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './grantedAuthority';


export interface Compte { 
    id?: number;
    status?: string;
    username?: string;
    updatedAt?: string;
    lastConnexion?: string;
    passwordChanged?: boolean;
    enabled?: boolean;
    accountNonLocked?: boolean;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
    authorities?: Array<GrantedAuthority>;
}

