/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Compte } from './compte';
import { Structure } from './structure';


export interface EmployeDto { 
    id?: number;
    lastName?: string;
    firstName?: string;
    email?: string;
    dateBirth?: string;
    mobile?: string;
    typeContratct?: string;
    dateBeginContract?: string;
    dateEndContract?: string;
    structure?: Structure;
    compte?: Compte;
    structureId?: number;
    getcompteId?: number;
    files?: Array<any>;
    statut?: string;
    structureName?: string;
}

