/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HoraireDto { 
    id?: number;
    jour?: HoraireDto.JourEnum;
    heureDebut?: string;
    heureFin?: string;
}
export namespace HoraireDto {
    export type JourEnum = 'LUNDI' | 'MARDI' | 'MERCREDI' | 'JEUDI' | 'VENDREDI';
    export const JourEnum = {
        Lundi: 'LUNDI' as JourEnum,
        Mardi: 'MARDI' as JourEnum,
        Mercredi: 'MERCREDI' as JourEnum,
        Jeudi: 'JEUDI' as JourEnum,
        Vendredi: 'VENDREDI' as JourEnum
    };
}


