/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PreInscription } from './preInscription';
import { Child } from './child';


export interface Horaire { 
    preInscription?: PreInscription;
    child?: Child;
    id?: number;
    jour?: Horaire.JourEnum;
    heureArrivee?: string;
    heureDepart?: string;
}
export namespace Horaire {
    export type JourEnum = 'LUNDI' | 'MARDI' | 'MERCREDI' | 'JEUDI' | 'VENDREDI';
    export const JourEnum = {
        Lundi: 'LUNDI' as JourEnum,
        Mardi: 'MARDI' as JourEnum,
        Mercredi: 'MERCREDI' as JourEnum,
        Jeudi: 'JEUDI' as JourEnum,
        Vendredi: 'VENDREDI' as JourEnum
    };
}


