/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Requête pour récupérer le menu visible d\'un utilisateur
 */
export interface MenuRequestDto { 
    /**
     * Rôle unique de l\'utilisateur
     */
    role: string;
}

