/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParentPreinscription { 
    id?: number;
    firstName?: string;
    lastName?: string;
    dateNaissance?: string;
    adresse?: string;
    telephoneDomicile?: string;
    telephonePortable?: string;
    email?: string;
    profession?: string;
}

