/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChildDto } from './childDto';


export interface ParentDto { 
    id?: number;
    lastName?: string;
    firstName?: string;
    email?: string;
    dateBirth?: string;
    mobile?: string;
    address?: string;
    profession?: string;
    familySituation?: string;
    secondParentLastName?: string;
    secondParentFirstName?: string;
    secondParentEmail?: string;
    secondParentMobile?: string;
    secondParentProfession?: string;
    secondParentFamilySituation?: string;
    structureId?: number;
    repositoryId?: number;
    children?: Array<ChildDto>;
    files?: Array<any>;
}

