/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Structure } from './structure';
import { Child } from './child';


export interface Parent { 
    id?: number;
    firstName?: string;
    lastName?: string;
    dateBirth?: string;
    createdAt?: string;
    updatedAt?: string;
    email?: string;
    mobile?: string;
    structure?: Structure;
    files?: Array<any>;
    profession?: string;
    familySituation?: string;
    secondParentProfession?: string;
    secondParentFamilySituation?: string;
    address_parent?: string;
    secondParentLastName?: string;
    secondParentFirstName?: string;
    secondParentEmail?: string;
    secondParentMobile?: string;
    children?: Array<Child>;
}

