/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Parent } from './parent';


export interface PaymentDto { 
    id?: number;
    month?: string;
    year?: string;
    amount?: number;
    dateTransfer?: string;
    createdAt?: string;
    status?: PaymentDto.StatusEnum;
    invoiceUrl?: string;
    comment?: string;
    parentId?: number;
    parent?: Parent;
}
export namespace PaymentDto {
    export type StatusEnum = 'EN_ATTENTE' | 'VALIDE' | 'REFUSE';
    export const StatusEnum = {
        EnAttente: 'EN_ATTENTE' as StatusEnum,
        Valide: 'VALIDE' as StatusEnum,
        Refuse: 'REFUSE' as StatusEnum
    };
}


