/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Structure } from './structure';


export interface Person { 
    id?: number;
    firstName?: string;
    lastName?: string;
    dateBirth?: string;
    createdAt?: string;
    updatedAt?: string;
    email?: string;
    mobile?: string;
    structure?: Structure;
    files?: Array<any>;
}

