/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Employe } from './employe';
import { Structure } from './structure';


export interface Rapport { 
    id?: number;
    bodyRapport?: string;
    dateCreated?: string;
    dateUpdated?: string;
    employes?: Set<Employe>;
    structure?: Structure;
}

