/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Candidate } from './candidate';
import { City } from './city';
import { Person } from './person';


export interface Structure { 
    id?: number;
    structureName?: string;
    capacity?: number;
    adresse?: string;
    mobile?: string;
    statut?: string;
    log?: number;
    lat?: number;
    createdAt?: string;
    avantages?: string;
    person?: Set<Person>;
    description?: string;
    images?: Array<string>;
    candidates?: Set<Candidate>;
    city?: City;
}

